local T, C, L = unpack(Tukui)

TukuiMinimap:ClearAllPoints()
TukuiMinimap:SetPoint("TOPRIGHT", UIParent, "TOPRIGHT", -10, -10)
TukuiMinimap:CreateBorder(false, false)
TukuiMinimap:HideInsets()
TukuiMinimap:SetBackdropBorderColor(0,0,0,0)
TukuiMinimap:SetBackdrop(nil)

-- TukuiMinimapCoord:RobSkin()
TukuiMinimapCoord:ClearAllPoints()
TukuiMinimapCoord:SetPoint("BOTTOMRIGHT", TukuiMinimap, "BOTTOMRIGHT", -2, 0)
TukuiMinimapCoord:StripTextures()
TukuiMinimapCoordText:SetFont(T.CreateFontString())

-- TukuiMinimapZone:SetTemplate("Transparent")
-- TukuiMinimapZone:HideInsets()
-- TukuiMinimapZone:SetBackdropBorderColor(0,0,0,0)
-- TukuiMinimapZone:CreateBorder(false, true)
TukuiMinimapZone:StripTextures()
TukuiMinimapZoneText:SetFont(T.CreateFontString())

TukuiTicket:RobSkin()
TukuiTicket:Size(23)
TukuiTicket.Text:SetText(T.RGBToHex(unpack(C["media"].datatextcolor1)).."T")
TukuiTicket.Text:SetFont(T.CreateFontString())
TukuiTicket:ClearAllPoints()
TukuiTicket:SetPoint("BOTTOMLEFT", TukuiMinimap, "BOTTOMLEFT", 2, 2)

local mapBG = CreateFrame("Frame", mapBG, TukuiMinimap)
mapBG:ClearAllPoints()
mapBG:SetPoint("TOPLEFT", 2, -2)
mapBG:SetPoint("BOTTOMRIGHT", -2, 2)
mapBG:Size(1, 1)
mapBG:SetTemplate("Default")
mapBG:CreateBorder(false, true)
mapBG:HideInsets()
mapBG:SetFrameStrata("Low")